name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.7.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build plugin
        run: pnpm build
      - name: Compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/ui,@grafana/runtime
