name: Release

on:
  push:
    tags:
      - "v*" # Run workflow on version tags, e.g. v1.0.0.

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.7.0
      - uses: grafana/plugin-actions/build-plugin@release
        with:
          node-version: "24"
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
